# Generated by Django 2.2.7 on 2019-12-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191206_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=5),
            preserve_default=False,
        ),
    ]
