# Generated by Django 2.2.7 on 2019-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='toppings',
        ),
        migrations.AddField(
            model_name='item',
            name='toppings',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
