# Generated by Django 2.2.7 on 2019-12-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191208_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
